SELECT * FROM CLIENTE;

SELECT * FROM TRANSACCION_PAGO;

SELECT * FROM RESERVA_TEMPORAL;

SELECT c.NOMBRE, rt.ESTADO AS ESTADO_DE_RESERVA, tp.MONTO_BRUTO, tp.DESCUENTO, tp.MONTO_FINAL, tp.ESTADO AS ESTADO_DE_PAGO FROM CLIENTE c 
JOIN RESERVA_TEMPORAL rt ON rt.CLIENTE_ID = c.CLIENTE_ID 
JOIN TRANSACCION_PAGO tp ON tp.RESERVA_ID = rt.RESERVA_ID
WHERE c.CLIENTE_ID = 1;


DECLARE 
    TYPE boleta_cliente IS RECORD(
        nombre_cliente CLIENTE.NOMBRE%TYPE,
        estado_reserva RESERVA_TEMPORAL.ESTADO%TYPE,
        monto_bruto TRANSACCION_PAGO.MONTO_BRUTO%TYPE,
        descuento_transaccion TRANSACCION_PAGO.DESCUENTO%TYPE,
        monto_final TRANSACCION_PAGO.MONTO_FINAL%TYPE,
        estado_transaccion TRANSACCION_PAGO.ESTADO%TYPE
    );

    v_boleta boleta_cliente;

BEGIN
    SELECT c.NOMBRE, rt.ESTADO AS ESTADO_DE_RESERVA, tp.MONTO_BRUTO, tp.DESCUENTO, tp.MONTO_FINAL, tp.ESTADO AS ESTADO_DE_PAGO INTO v_boleta.nombre_cliente, v_boleta.estado_reserva INCOMPLETOOO!!!!!!!!!!!    FROM CLIENTE c 
    JOIN RESERVA_TEMPORAL rt ON rt.CLIENTE_ID = c.CLIENTE_ID 
    JOIN TRANSACCION_PAGO tp ON tp.RESERVA_ID = rt.RESERVA_ID
    WHERE c.CLIENTE_ID = 1;
    null; 
END;